# Generated by Django 4.1.5 on 2023-01-08 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_game_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(default="start_game", max_length=15),
        ),
        migrations.AlterField(
            model_name="game",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 8, 13, 43, 35, 789759)
            ),
        ),
    ]
